# Metadatos, no modificar.
# Default: 0
configVersion = 3

[general]

	# Activa o desactiva todas las características del mod.
	# Default: true
	enabled = true
	# Desactiva esto para hacer que los efectos del mod sean exclusivos de la vista en primera persona.
	# Default: true
	enableInThirdPerson = true
	# How smooth should transitions between contextual profiles such as walking and swimming be.
	# Default: 0.1
	contextTransitionSmoothing = 0.1
	# Sensibilidad de la rotación de inclinación de la cámara causada por girar horizontalmente.
	# Default: 1.0
	turningRollAccumulation = 1.0
	# Fuerza máxima de la rotación de inclinación de la cámara causada por girar horizontalmente.
	# Default: 1.25
	turningRollIntensity = 1.25
	# Suavidad de la disminución de la rotación de inclinación de la cámara causada por girar horizontalmente.
	# Default: 1.0
	turningRollSmoothing = 1.0
	# Fuerza del balanceo suave y aleatorio que se activa cuando el jugador permanece inactivo durante suficiente tiempo.
	# Default: 0.6
	cameraSwayIntensity = 0.6
	# Frecuencia del balanceo suave y aleatorio que se activa cuando el jugador permanece inactivo durante suficiente tiempo.
	# Default: 0.16
	cameraSwayFrequency = 0.16
	# Cantidad de tiempo que el jugador debe permanecer inactivo antes de que el balanceo suave y aleatorio comience a aparecer.
	# Default: 0.15
	cameraSwayFadeInDelay = 0.15
	# Cantidad de tiempo que tarda el balanceo suave y aleatorio en aparecer después de que el jugador permanece inactivo durante suficiente tiempo.
	# Default: 5.0
	cameraSwayFadeInLength = 5.0
	# Cantidad de tiempo que tarda el balanceo suave y aleatorio en desaparecer cuando el jugador comienza a moverse después de estar inactivo.
	# Default: 0.75
	cameraSwayFadeOutLength = 0.75
	# Fuerza máxima de todos los efectos de sacudidas de pantalla.
	# Default: 2.5
	screenShakesMaxIntensity = 2.5
	# Velocidad a la que las rotaciones de sacudidas de pantalla cambian de dirección u oscilan.
	# Default: 6.0
	screenShakesMaxFrequency = 6.0
	# Un valor [0..1] vinculado a la fuerza de las sacudidas de pantalla causadas por explosiones.
	# Default: 1.0
	explosionTrauma = 1.0
	# Un valor [0..1] vinculado a la fuerza de las sacudidas de pantalla causadas por el trueno de un rayo.
	# Default: 0.05
	thunderTrauma = 0.05
	# Un valor [0..1] vinculado a la fuerza de las sacudidas de pantalla causadas por cualquier acción que balancee el brazo del jugador. Mejor mantenerlo muy bajo.
	# Default: 0.03
	handSwingTrauma = 0.03

[walking]

	# Fuerza de la rotación de inclinación de la cámara causada por el desplazamiento lateral o la velocidad horizontal lateral.
	# Default: 10.0
	strafingRollFactor = 10.0
	# Fuerza de las rotaciones de inclinación de la cámara causadas por moverse hacia adelante o hacia atrás.
	# Default: 7.0
	forwardVelocityPitchFactor = 7.0
	# Fuerza de las rotaciones de inclinación de la cámara causadas por la velocidad vertical.
	# Default: 2.5
	verticalVelocityPitchFactor = 2.5
	# Suavidad de las rotaciones de inclinación y balanceo de la cámara causadas por moverse horizontalmente.
	# Default: 1.0
	horizontalVelocitySmoothingFactor = 1.0
	# Suavidad de las rotaciones de inclinación de la cámara causadas por moverse verticalmente.
	# Default: 1.0
	verticalVelocitySmoothingFactor = 1.0
	# Controls global interpolation of the camera's pitch & yaw. Does not affect gameplay (aim).
	# Default: 0.0
	cameraSmoothing = 0.0

[sprinting]

	# Fuerza de la rotación de inclinación de la cámara causada por el desplazamiento lateral o la velocidad horizontal lateral.
	# Default: 12.5
	strafingRollFactor = 12.5
	# Fuerza de las rotaciones de inclinación de la cámara causadas por moverse hacia adelante o hacia atrás.
	# Default: 9.5
	forwardVelocityPitchFactor = 9.5
	# Fuerza de las rotaciones de inclinación de la cámara causadas por la velocidad vertical.
	# Default: 2.5
	verticalVelocityPitchFactor = 2.5
	# Suavidad de las rotaciones de inclinación y balanceo de la cámara causadas por moverse horizontalmente.
	# Default: 1.0
	horizontalVelocitySmoothingFactor = 1.0
	# Suavidad de las rotaciones de inclinación de la cámara causadas por moverse verticalmente.
	# Default: 1.0
	verticalVelocitySmoothingFactor = 1.0
	# Controls global interpolation of the camera's pitch & yaw. Does not affect gameplay (aim).
	# Default: 0.6
	cameraSmoothing = 0.6

[swimming]

	# Fuerza de la rotación de inclinación de la cámara causada por el desplazamiento lateral o la velocidad horizontal lateral.
	# Default: -30.0
	strafingRollFactor = -30.0
	# Fuerza de las rotaciones de inclinación de la cámara causadas por moverse hacia adelante o hacia atrás.
	# Default: 21.0
	forwardVelocityPitchFactor = 21.0
	# Fuerza de las rotaciones de inclinación de la cámara causadas por la velocidad vertical.
	# Default: 7.5
	verticalVelocityPitchFactor = 7.5
	# Suavidad de las rotaciones de inclinación y balanceo de la cámara causadas por moverse horizontalmente.
	# Default: 1.0
	horizontalVelocitySmoothingFactor = 1.0
	# Suavidad de las rotaciones de inclinación de la cámara causadas por moverse verticalmente.
	# Default: 1.0
	verticalVelocitySmoothingFactor = 1.0
	# Controls global interpolation of the camera's pitch & yaw. Does not affect gameplay (aim).
	# Default: 1.5
	cameraSmoothing = 1.5

[flying]

	# Fuerza de la rotación de inclinación de la cámara causada por el desplazamiento lateral o la velocidad horizontal lateral.
	# Default: -10.0
	strafingRollFactor = -10.0
	# Fuerza de las rotaciones de inclinación de la cámara causadas por moverse hacia adelante o hacia atrás.
	# Default: 7.0
	forwardVelocityPitchFactor = 7.0
	# Fuerza de las rotaciones de inclinación de la cámara causadas por la velocidad vertical.
	# Default: 2.5
	verticalVelocityPitchFactor = 2.5
	# Suavidad de las rotaciones de inclinación y balanceo de la cámara causadas por moverse horizontalmente.
	# Default: 1.0
	horizontalVelocitySmoothingFactor = 1.0
	# Suavidad de las rotaciones de inclinación de la cámara causadas por moverse verticalmente.
	# Default: 1.0
	verticalVelocitySmoothingFactor = 1.0
	# Controls global interpolation of the camera's pitch & yaw. Does not affect gameplay (aim).
	# Default: 1.0
	cameraSmoothing = 1.0

[mounts]

	# Fuerza de la rotación de inclinación de la cámara causada por el desplazamiento lateral o la velocidad horizontal lateral.
	# Default: 20.0
	strafingRollFactor = 20.0
	# Fuerza de las rotaciones de inclinación de la cámara causadas por moverse hacia adelante o hacia atrás.
	# Default: 3.5
	forwardVelocityPitchFactor = 3.5
	# Fuerza de las rotaciones de inclinación de la cámara causadas por la velocidad vertical.
	# Default: 2.5
	verticalVelocityPitchFactor = 2.5
	# Suavidad de las rotaciones de inclinación y balanceo de la cámara causadas por moverse horizontalmente.
	# Default: 1.0
	horizontalVelocitySmoothingFactor = 1.0
	# Suavidad de las rotaciones de inclinación de la cámara causadas por moverse verticalmente.
	# Default: 1.0
	verticalVelocitySmoothingFactor = 1.0
	# Controls global interpolation of the camera's pitch & yaw. Does not affect gameplay (aim).
	# Default: 1.0
	cameraSmoothing = 1.0

[vehicles]

	# Fuerza de la rotación de inclinación de la cámara causada por el desplazamiento lateral o la velocidad horizontal lateral.
	# Default: 5.0
	strafingRollFactor = 5.0
	# Fuerza de las rotaciones de inclinación de la cámara causadas por moverse hacia adelante o hacia atrás.
	# Default: 3.5
	forwardVelocityPitchFactor = 3.5
	# Fuerza de las rotaciones de inclinación de la cámara causadas por la velocidad vertical.
	# Default: 5.0
	verticalVelocityPitchFactor = 5.0
	# Suavidad de las rotaciones de inclinación y balanceo de la cámara causadas por moverse horizontalmente.
	# Default: 1.0
	horizontalVelocitySmoothingFactor = 1.0
	# Suavidad de las rotaciones de inclinación de la cámara causadas por moverse verticalmente.
	# Default: 1.0
	verticalVelocitySmoothingFactor = 1.0
	# Controls global interpolation of the camera's pitch & yaw. Does not affect gameplay (aim).
	# Default: 0.0
	cameraSmoothing = 0.0
